"""
reference/config.py — Instrument universe and underlying definitions.

Self-contained in the live-trading repo; no orb_event_study dependency.
Only INSTRUMENTS and UNDERLYINGS are consumed by the live system.
"""

INSTRUMENTS = {
    # ── G1: Tight basket arbitrage ────────────────────────────────────────
    "TQQQ": {"underlying": "QQQ",  "inverse": False, "leverage": 3},
    "SQQQ": {"underlying": "QQQ",  "inverse": True,  "leverage": 3},
    "QLD":  {"underlying": "QQQ",  "inverse": False, "leverage": 2},
    "QID":  {"underlying": "QQQ",  "inverse": True,  "leverage": 2},
    "SPXL": {"underlying": "SPY",  "inverse": False, "leverage": 3},
    "SPXS": {"underlying": "SPY",  "inverse": True,  "leverage": 3},
    "SSO":  {"underlying": "SPY",  "inverse": False, "leverage": 2},
    "SDS":  {"underlying": "SPY",  "inverse": True,  "leverage": 2},
    "TNA":  {"underlying": "IWM",  "inverse": False, "leverage": 3},
    "TZA":  {"underlying": "IWM",  "inverse": True,  "leverage": 3},
    "FAS":  {"underlying": "XLF",  "inverse": False, "leverage": 3},
    "FAZ":  {"underlying": "XLF",  "inverse": True,  "leverage": 3},
    "FNGU": {"underlying": "QQQ",  "inverse": False, "leverage": 3},
    "FNGD": {"underlying": "QQQ",  "inverse": True,  "leverage": 3},

    # ── G2: Commodity futures arb ─────────────────────────────────────────
    "BOIL": {"underlying": "UNG",  "inverse": False, "leverage": 2},
    "KOLD": {"underlying": "UNG",  "inverse": True,  "leverage": 2},
    "UCO":  {"underlying": "USO",  "inverse": False, "leverage": 2},
    "SCO":  {"underlying": "USO",  "inverse": True,  "leverage": 2},
    "OILU": {"underlying": "USO",  "inverse": False, "leverage": 2},
    "ERX":  {"underlying": "XLE",  "inverse": False, "leverage": 2},
    "ERY":  {"underlying": "XLE",  "inverse": True,  "leverage": 2},
    "UGL":  {"underlying": "GLD",  "inverse": False, "leverage": 2},
    "GLL":  {"underlying": "GLD",  "inverse": True,  "leverage": 2},
    "SHNY": {"underlying": "SLV",  "inverse": False, "leverage": 2},
    "AGQ":  {"underlying": "SLV",  "inverse": False, "leverage": 2},
    "ZSL":  {"underlying": "SLV",  "inverse": True,  "leverage": 2},
    "NUGT": {"underlying": "GDX",  "inverse": False, "leverage": 2},
    "DUST": {"underlying": "GDX",  "inverse": True,  "leverage": 2},
    "JNUG": {"underlying": "GDXJ", "inverse": False, "leverage": 2},
    "JDST": {"underlying": "GDXJ", "inverse": True,  "leverage": 2},

    # ── G3: Structural non-arb (binary event driven) ──────────────────────
    "LABU": {"underlying": "IBB",  "inverse": False, "leverage": 3},
    "LABD": {"underlying": "IBB",  "inverse": True,  "leverage": 3},
    "BIB":  {"underlying": "IBB",  "inverse": False, "leverage": 2},
    "BIS":  {"underlying": "IBB",  "inverse": True,  "leverage": 2},

    # ── G4: Crypto ────────────────────────────────────────────────────────
    "ETHU": {"underlying": "ETH",  "inverse": False, "leverage": 2},
    "ETHD": {"underlying": "ETH",  "inverse": True,  "leverage": 2},
    "BITX": {"underlying": "BTC",  "inverse": False, "leverage": 2},
    "BITU": {"underlying": "BTC",  "inverse": False, "leverage": 2},
    "SBIT": {"underlying": "BTC",  "inverse": True,  "leverage": 2},
    "BITI": {"underlying": "BTC",  "inverse": True,  "leverage": 1},
    "IBIT": {"underlying": "BTC",  "inverse": False, "leverage": 1},
    "FBTC": {"underlying": "BTC",  "inverse": False, "leverage": 1},
    "GBTC": {"underlying": "BTC",  "inverse": False, "leverage": 1},
    "ETHA": {"underlying": "ETH",  "inverse": False, "leverage": 1},
    "ETHW": {"underlying": "ETH",  "inverse": False, "leverage": 1},
    "CETH": {"underlying": "ETH",  "inverse": False, "leverage": 1},
    "BTCL": {"underlying": "BTC",  "inverse": False, "leverage": 2},
    "BTCZ": {"underlying": "BTC",  "inverse": True,  "leverage": 2},
    "ETHT": {"underlying": "ETH",  "inverse": False, "leverage": 2},
    "ETU":  {"underlying": "ETH",  "inverse": False, "leverage": 2},
    "SOLT": {"underlying": "SOL",  "inverse": False, "leverage": 2},
    "SOLX": {"underlying": "SOL",  "inverse": False, "leverage": 2},
    "XRPT": {"underlying": "XRP",  "inverse": False, "leverage": 2},
    "UXRP": {"underlying": "XRP",  "inverse": False, "leverage": 2},

    # ── G5: Crypto-adjacent equity ────────────────────────────────────────
    "MSTU": {"underlying": "MSTR", "inverse": False, "leverage": 2},
    "MSTX": {"underlying": "MSTR", "inverse": False, "leverage": 2},
    "CONL": {"underlying": "COIN", "inverse": False, "leverage": 2},

    # ── G6: Asian-market equity ───────────────────────────────────────────
    "SOXL": {"underlying": "SOXX", "inverse": False, "leverage": 3},
    "SOXS": {"underlying": "SOXX", "inverse": True,  "leverage": 3},
    "EDC":  {"underlying": "EEM",  "inverse": False, "leverage": 3},
    "EDZ":  {"underlying": "EEM",  "inverse": True,  "leverage": 3},
    "YINN": {"underlying": "FXI",  "inverse": False, "leverage": 3},
    "YANG": {"underlying": "FXI",  "inverse": True,  "leverage": 3},
    "KORU": {"underlying": "EWY",  "inverse": False, "leverage": 3},
    "TSMX": {"underlying": "TSM",  "inverse": False, "leverage": 2},

    # ── G7: Single stock leveraged ────────────────────────────────────────
    "NVDL": {"underlying": "NVDA", "inverse": False, "leverage": 2},
    "NVDU": {"underlying": "NVDA", "inverse": False, "leverage": 2},
    "TSLL": {"underlying": "TSLA", "inverse": False, "leverage": 2},
    "AMDL": {"underlying": "AMD",  "inverse": False, "leverage": 2},
    "AAPU": {"underlying": "AAPL", "inverse": False, "leverage": 2},
    "AMZU": {"underlying": "AMZN", "inverse": False, "leverage": 2},
    "METU": {"underlying": "META", "inverse": False, "leverage": 2},
    "MSFU": {"underlying": "MSFT", "inverse": False, "leverage": 2},
    "GGLL": {"underlying": "GOOGL","inverse": False, "leverage": 2},
    "NFXL": {"underlying": "NFLX", "inverse": False, "leverage": 2},
    "SMCL": {"underlying": "SMCI", "inverse": False, "leverage": 2},
    "GMEU": {"underlying": "GME",  "inverse": False, "leverage": 2},
    "APPX": {"underlying": "APP",  "inverse": False, "leverage": 2},
    "SNOU": {"underlying": "SNOW", "inverse": False, "leverage": 2},
    "KMLI": {"underlying": "MELI", "inverse": False, "leverage": 2},

    # ── G8: Volatility ────────────────────────────────────────────────────
    "UVXY": {"underlying": "VIX",  "inverse": False, "leverage": 1.5},
    "UVIX": {"underlying": "VIX",  "inverse": False, "leverage": 2},
    "SVIX": {"underlying": "VIX",  "inverse": True,  "leverage": 1},
    "VIXY": {"underlying": "VIX",  "inverse": False, "leverage": 1},
    "SVXY": {"underlying": "VIX",  "inverse": True,  "leverage": 0.5},
    "VIXM": {"underlying": "VIX",  "inverse": False, "leverage": 1},

    # ── G9: Technology sector ─────────────────────────────────────────────
    "TECL": {"underlying": "XLK",  "inverse": False, "leverage": 3},
    "TECS": {"underlying": "XLK",  "inverse": True,  "leverage": 3},
    "ROM":  {"underlying": "XLK",  "inverse": False, "leverage": 2},
    "REW":  {"underlying": "XLK",  "inverse": True,  "leverage": 2},
    "WEBL": {"underlying": "XLC",  "inverse": False, "leverage": 3},
    "WEBS": {"underlying": "XLC",  "inverse": True,  "leverage": 3},

    # ── G10: Treasury bonds ───────────────────────────────────────────────
    "TMF":  {"underlying": "TLT",  "inverse": False, "leverage": 3},
    "TMV":  {"underlying": "TLT",  "inverse": True,  "leverage": 3},
    "UBT":  {"underlying": "TLT",  "inverse": False, "leverage": 2},
    "TBT":  {"underlying": "TLT",  "inverse": True,  "leverage": 2},
    "TYD":  {"underlying": "IEF",  "inverse": False, "leverage": 3},
    "TYO":  {"underlying": "IEF",  "inverse": True,  "leverage": 3},

    # ── G11: Healthcare ───────────────────────────────────────────────────
    "CURE": {"underlying": "XLV",  "inverse": False, "leverage": 3},

    # ── G12: Sector / Thematic ────────────────────────────────────────────
    "DPST": {"underlying": "KRE",  "inverse": False, "leverage": 3},
    "RETL": {"underlying": "XRT",  "inverse": False, "leverage": 3},
    "NAIL": {"underlying": "ITB",  "inverse": False, "leverage": 3},

    # ── G13: Broad market / International ────────────────────────────────
    "UDOW": {"underlying": "DIA",  "inverse": False, "leverage": 3},
    "SDOW": {"underlying": "DIA",  "inverse": True,  "leverage": 3},
    "INDL": {"underlying": "INDY", "inverse": False, "leverage": 3},
    "CWEB": {"underlying": "KWEB", "inverse": False, "leverage": 2},

    # ── G14: International equity ─────────────────────────────────────────
    "MIDU": {"underlying": "MDY",  "inverse": False, "leverage": 3},
    "EZJ":  {"underlying": "EWJ",  "inverse": False, "leverage": 2},
    "EURL": {"underlying": "FEZ",  "inverse": False, "leverage": 3},
    "UPV":  {"underlying": "VGK",  "inverse": False, "leverage": 2},
    "MEXX": {"underlying": "EWW",  "inverse": False, "leverage": 3},
    "CHAU": {"underlying": "ASHR", "inverse": False, "leverage": 2},
    "BRZU": {"underlying": "EWZ",  "inverse": False, "leverage": 2},
    "UBR":  {"underlying": "EWZ",  "inverse": False, "leverage": 2},

    # ── G15: Energy & Aerospace ───────────────────────────────────────────
    "DFEN": {"underlying": "ITA",  "inverse": False, "leverage": 3},
    "NRGU": {"underlying": "XOP",  "inverse": False, "leverage": 3},
    "GUSH": {"underlying": "XOP",  "inverse": False, "leverage": 2},

    # ── G16: Real Estate ──────────────────────────────────────────────────
    "DRN":  {"underlying": "IYR",  "inverse": False, "leverage": 3},
    "URE":  {"underlying": "IYR",  "inverse": False, "leverage": 2},

    # ── G17: Sector additions ─────────────────────────────────────────────
    "BNKU": {"underlying": "KBE",  "inverse": False, "leverage": 3},
    "PILL": {"underlying": "IHE",  "inverse": False, "leverage": 3},
    "WANT": {"underlying": "XLY",  "inverse": False, "leverage": 3},
    "UTSL": {"underlying": "XLU",  "inverse": False, "leverage": 3},
    "UYM":  {"underlying": "XLB",  "inverse": False, "leverage": 2},
    "DUSL": {"underlying": "XLI",  "inverse": False, "leverage": 3},
    "UXI":  {"underlying": "XLI",  "inverse": False, "leverage": 2},

    # ── G18: Broad market additions ───────────────────────────────────────
    "UPRO": {"underlying": "SPY",  "inverse": False, "leverage": 3},
    "URTY": {"underlying": "IWM",  "inverse": False, "leverage": 3},
    "SRTY": {"underlying": "IWM",  "inverse": True,  "leverage": 3},
    "UGE":  {"underlying": "XLP",  "inverse": False, "leverage": 2},
}

UNDERLYINGS = {
    "BTC":   "crypto",
    "ETH":   "crypto",
    "SOL":   "crypto",
    "XRP":   "crypto",
    "LINK":  "crypto",
    "ADA":   "crypto",
    "XLM":   "crypto",
    "SPY":   "equity",
    "QQQ":   "equity",
    "IWM":   "equity",
    "XLF":   "equity",
    "XLE":   "equity",
    "IBB":   "equity",
    "IHE":   "equity",
    "GDX":   "equity",
    "GDXJ":  "equity",
    "SOXX":  "equity",
    "SMH":   "equity",
    "EEM":   "equity",
    "VWO":   "equity",
    "FXI":   "equity",
    "EWY":   "equity",
    "GLD":   "equity",
    "SLV":   "equity",
    "USO":   "equity",
    "UNG":   "equity",
    "COIN":  "equity",
    "MSTR":  "equity",
    "NVDA":  "equity",
    "TSLA":  "equity",
    "AAPL":  "equity",
    "AMZN":  "equity",
    "META":  "equity",
    "MSFT":  "equity",
    "GOOGL": "equity",
    "NFLX":  "equity",
    "TSM":   "equity",
    "SMCI":  "equity",
    "GME":   "equity",
    "APP":   "equity",
    "SNOW":  "equity",
    "MELI":  "equity",
    "AMD":   "equity",
    "VIX":   "index",
    "XLK":   "equity",
    "XLC":   "equity",
    "XLV":   "equity",
    "IYR":   "equity",
    "TLT":   "equity",
    "IEF":   "equity",
    "KRE":   "equity",
    "XRT":   "equity",
    "ITB":   "equity",
    "DIA":   "equity",
    "INDY":  "equity",
    "KWEB":  "equity",
    "ASHR":  "equity",
    "ITA":   "equity",
    "XOP":   "equity",
    "EWJ":   "equity",
    "MDY":   "equity",
    "KBE":   "equity",
    "EWW":   "equity",
    "FEZ":   "equity",
    "VGK":   "equity",
    "EWZ":   "equity",
    "XLY":   "equity",
    "XLU":   "equity",
    "XLB":   "equity",
    "XLP":   "equity",
    "XLI":   "equity",
}
